CREATE TABLE IF NOT EXISTS medical_services (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  category VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS offices (
  id BIGSERIAL PRIMARY KEY,
  city VARCHAR(80) NOT NULL UNIQUE,
  role VARCHAR(100) NOT NULL,
  employees INTEGER NOT NULL CHECK (employees >= 0)
);
