CREATE TABLE IF NOT EXISTS medical_services (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  category VARCHAR(80) NOT NULL,
  image_url VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS offices (
  id BIGSERIAL PRIMARY KEY,
  city VARCHAR(80) NOT NULL UNIQUE,
  role VARCHAR(100) NOT NULL,
  employees INTEGER NOT NULL CHECK (employees >= 0)
);

CREATE TABLE IF NOT EXISTS teleconsultations (
  id BIGSERIAL PRIMARY KEY,
  patient_name VARCHAR(120) NOT NULL,
  doctor_name VARCHAR(120) NOT NULL,
  speciality VARCHAR(120) NOT NULL,
  scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(40) NOT NULL,
  reason VARCHAR(500) NOT NULL
);
